### ISSUE TITLE
RSS/SNS Subscription for New Linux AMI Release

### ISSUE THREAD

**Issue by Ramneek-kalra** [aws/amazon-ecs-ami#107]
### Summary

Team, do we have RSS/SNS Subscription for New ECS Optimized AMI Release?

### Description

I can see for Windows at: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS-AMI-windows-SubscribeTopic.html

Do we have it setup for Linux AMIs as well?

**Comment by danehlim** [comment]
Hello @Ramneek-kalra, thank you for your inquiry. According to [this issue in the awsdocs repository](https://github.com/awsdocs/amazon-ecs-developer-guide/issues/184#issuecomment-933617387), there **used to** exist an SNS notification ARN for Amazon ECS-optimized Linux AMI, but it **has been deprecated**. Thus, there currently is no SNS topic that notifies when a specific new Amazon ECS-optimized Linux AMI variant is released.

**Comment by danehlim** [comment]
Our team does create separate [SSM Parameter Store parameters for each ECS-optimized Linux AMI variant](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html
), so each one can be queried at any point to retrieve the latest AMI ID. One possible workaround could be to:

1. Check your desired ECS-Optimized AMI's SSM parameters and save the value somewhere
2. Create a custom AWS Lambda function that:
  - checks the current SSM parameters of your desired ECS-Optimized AMI differs from the saved value
  - saves the new value and sends a message to a specified SNS topic if the values differ
3. Schedule AWS Lambda  function to be invoked on a regular/recurring basis (e.g., by using EventBridge or some other job scheduling mechanism)
