### ISSUE TITLE
Proposed updates to the changelog

### ISSUE THREAD

**Issue by joelbrandenburg** [aws/amazon-ecs-ami#122]
### Summary
I recommend we make updates to the AMI changelog to provide more details that customers need.

### Description
I'm proposing making the following updates to the changelog for each AMI released:
1) Include the container agent and Docker versions included with each AMI
2) Add details about any new feature support included in the AMI.  I know feature support is via the agent version but I think it'd help to see this relayed on the AMI changelog as well.

**Comment by chienhanlin** [comment]
Thanks for sharing this proposal with us. We have updated the changelog with more details, including Docker and containerd update, and start working release notes. Please take a look on the latest release notes [here](https://github.com/aws/amazon-ecs-ami/releases). Thanks.
