### ISSUE TITLE
Downgrade of Docker from 20.10.23 to 20.10.22 in latest release?

### ISSUE THREAD

**Issue by tangix** [aws/amazon-ecs-ami#128]
### Summary
I recently (~May 5) upgraded ECS to run optimized AMI `ami-09822cbc47b3c1ce2` (in `eu-central-1` region). 
On May 9, a new version was released: `ami-062c116e449466e7f`. 
The new AMI seems to have downgraded Docker. 
Is this intentional?

### Description
From the ECS console running `ami-098*`:
<img width="1277" alt="image" src="https://github.com/aws/amazon-ecs-ami/assets/1013635/ece87782-c29a-42f9-adde-330c87ad3330">

From query of SSM to get latest optimized AMI I see the following metadata:
```
$ aws ssm get-parameters --profile ecs-registry \
--names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended \
--region eu-central-1
{
    "Parameters": [
        {
            "Name": "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended",
            "Type": "String",
            "Value": "{\"ecs_agent_version\":\"1.71.1\",\"ecs_runtime_version\":\"Docker version 20.10.22\",\"image_id\":\"ami-062c116e449466e7f\",\"image_name\":\"amzn2-ami-ecs-hvm-2.0.20230509-x86_64-ebs\",\"image_version\":\"2.0.20230509\",\"os\":\"Amazon Linux 2\",\"schema_version\":1,\"source_image_name\":\"amzn2-ami-minimal-hvm-2.0.20230504.1-x86_64-ebs\"}",
            "Version": 112,
            "LastModifiedDate": 1684174005.96,
            "ARN": "arn:aws:ssm:eu-central-1::parameter/aws/service/ecs/optimized-ami/amazon-linux-2/recommended",
            "DataType": "text"
        }
    ],
    "InvalidParameters": []
}
```

### Expected Behavior
Docker the same or newer version as previous AMI.

### Observed Behavior
Docker downgraded from 20.10.23.

**Comment by Realmonia** [comment]
Hi @tangix , maybe you have run `yum update` on your instance? For ECS optimized AMI we haven't qualify 20.10.23 yet, so the AMI comes with 20.10.22 with both 1.71.0 and 1.71.1, but it is available in Amazon Linux Repo so after you ran `yum update` docker will be upgraded.

See our release note with docker version: https://github.com/aws/amazon-ecs-ami/releases

If you want 20.10.23 in 1.71.1, you can run `yum update`.
