### ISSUE TITLE
Amazon ECS-optimized Amazon Linux 2 AMI GPU (Kernel 4.14) -- CUDA update to 11.8

### ISSUE THREAD

**Issue by hlo-world** [aws/amazon-ecs-ami#136]
### Summary
Feature request for CUDA update to 11.8

**Comment by danehlim** [comment]
ECS Optimized AMIs use the latest CUDA version available from Amazon Linux Repo. Currently the latest CUDA version available there is 11.4. Unfortunately, we cannot comment on behalf of [Amazon Linux](https://github.com/amazonlinux on if/when they plan on pushing CUDA updates (such as v11.8) to the amzn2-nvidia repo. If you require further information on this, please feel free to reach out to them.

**Comment by danehlim** [comment]
ECS Optimized AMIs use the latest CUDA version available from Amazon Linux Repo. Currently the latest CUDA version available there is 11.4. Unfortunately, we cannot comment on behalf of [Amazon Linux](https://github.com/amazonlinux) on if/when they plan on pushing CUDA updates (such as v11.8) to the amzn2-nvidia repo. If you require further information on this, please feel free to reach out to them.
