### ISSUE TITLE
ECS GPU image on 20230912 jumped to Nvidia 535 driver and Cuda 12.2

### ISSUE THREAD

**Issue by risdenk** [aws/amazon-ecs-ami#151]
### Summary
ECS GPU image jumped major CUDA version and GPU driver version in mid september

https://github.com/aws/amazon-ecs-ami/releases/tag/20230906

```
GPU (Kernel 4.14)
AMI name: amzn2-ami-ecs-gpu-hvm-2.0.20230906-x86_64-ebs
ECS Agent version: 1.75.3
Docker version: 20.10.23
Containerd version: 1.6.19
NVIDIA driver version: 470.182.03
CUDA version: 11.4
Source AMI name: amzn2-ami-minimal-hvm-2.0.20230822.0-x86_64-ebs
```

vs 

https://github.com/aws/amazon-ecs-ami/releases/tag/20230912
```
GPU (Kernel 4.14)
AMI name: amzn2-ami-ecs-gpu-hvm-2.0.20230912-x86_64-ebs
ECS Agent version: 1.76.0
Docker version: 20.10.23
Containerd version: 1.6.19
NVIDIA driver version: 535.54.03
CUDA version: 12.2.0
Source AMI name: amzn2-ami-minimal-hvm-2.0.20230906.0-x86_64-ebs
```

After poking around I found https://github.com/amazonlinux/amazon-linux-2023/issues/168 which details that https://github.com/aws/amazon-ecs-ami/blob/main/scripts/enable-ecs-agent-gpu-support.sh#L13-L44 is how the GPU driver is chosen. That explains why GPU details aren't found in https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20230911.html.

Also found https://github.com/aws/amazon-ecs-ami/issues/136 which states apparently this can just happen.

Just raising awareness since this doesn't seem to be called out anywhere else.

Are these types of jumps to be expected?

**Comment by singholt** [comment]
Hi @risdenk,

Thanks for reaching out. Yes you're right the latest ECS Optimized GPU AMIs starting 20230912 have the nvidia 535 and cuda 12 versions. 

We've updated our [ECS public documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html#p2-instance) with options if you'd like to continue using the older nvidia and cuda versions.

Closing this issue, please reopen if you have any questions.
