### ISSUE TITLE
Add support for Amazon EC2 Instance Connect

### ISSUE THREAD

**Issue by dali546** [aws/amazon-ecs-ami#170]
### Summary

ECS Machines can be accessed via SSM, using the `aws-ssm-agent`. It would be nice if you can also add `aws-ec2-instance-connect` too, allowing another way for systems that use EC2 Instance Connect

### Description

-

**Comment by danehlim** [comment]
Hello, thank you for your request! Our product team will continue to look into this as a feature request and track it here: https://github.com/aws/containers-roadmap/issues/1300

I will be closing this issue for now in favor of the above. Please refer to the workaround provided by @chienhanlin if you urgently need this functionality. I will also post about the workaround in the linked issue above.
