### ISSUE TITLE
Support M7a instance family

### ISSUE THREAD

**Issue by simis2626** [aws/amazon-ecs-ami#188]
### Summary
These images currently are not built to support M7a instance family types.

### Description
Trying to create a launch config or template using the x86_64 ecs ami with a M7a instance type gives the following error
<Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>The specified instance type m7a.xlarge is not valid</Message>
  </Error>

From the following content (some values removed)
Action=CreateLaunchConfiguration&AssociatePublicIpAddress=true&BlockDeviceMappings.member.1.DeviceName=%2Fdev%2Fxvda&BlockDeviceMappings.member.1.Ebs.DeleteOnTermination=true&BlockDeviceMappings.member.1.Ebs.Encrypted=false&BlockDeviceMappings.member.1.Ebs.SnapshotId=snap-03a4f8d1608c00a0b&BlockDeviceMappings.member.1.Ebs.VolumeSize=30&BlockDeviceMappings.member.1.Ebs.VolumeType=gp2&ClassicLinkVPCSecurityGroups=&EbsOptimized=false&IamInstanceProfile=arn%3Aaws%3Aiam%3A%3A071452343123%3Ainstance-profile%2FecsInstanceRole&ImageId=ami-0d63309a12899f79d&InstanceMonitoring.Enabled=false&InstanceType=m7a.xlarge&Version=2011-01-01

### Expected Behavior
Should be able to create launch template or configs using M7a instance types

### Observed Behavior
Receive errors that M7a.medium / xlarge are not supported.
![image](https://github.com/aws/amazon-ecs-ami/assets/18462964/7e54ba4a-0e13-419d-b176-2c2f3b53ed06)
![image](https://github.com/aws/amazon-ecs-ami/assets/18462964/2ed243ce-f794-43fe-bee4-bc21118fd5fc)

Note that M6a instance types are supported
![image](https://github.com/aws/amazon-ecs-ami/assets/18462964/0e714d18-1814-4ee9-9a72-4da46bf69caa)

The reason this impacts me is I'm looking to use the M7a.medium (where an equivalent small/cheap instance isn't available in the M6a family)

Thanks for considering this.

**Comment by sparrc** [comment]
This error is being returned from [CreateLaunchConfiguration](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CreateLaunchConfiguration.html), which is part of the EC2 autoscaling team, not ECS. If you have an issue with this API please contact AWS support.
