### ISSUE TITLE
Support GPU-based instances with ARM processors (G5g family)

### ISSUE THREAD

**Issue by rdelcampog** [aws/amazon-ecs-ami#220]
As of now, AWS maintains:

- Amazon ECS-optimized Amazon Linux 2023 (arm64) AMI
- Amazon ECS-optimized Amazon Linux 2 (arm64) AMI
- Amazon ECS GPU-optimized Amazon Linux 2 (x86_64) AMI

Would it be possible to have either:

- Amazon ECS GPU-optimized Amazon Linux 2023 (arm64) AMI
- Amazon ECS GPU-optimized Amazon Linux 2 (arm64) AMI

This will allow us to use Amazon EC2 instance pools to run GPU-capable containers in Graviton-powered instances, like the `G5g` family.

Thank you!

**Comment by rdelcampog** [comment]
cc/ @Yiyuanzzz @danehlim @mye956

**Comment by sparrc** [comment]
Hi @rdelcampog, thank you for the feature request, the ECS team can support this instance type as soon as we have available ARM NVIDIA packages in the AL2023 yum repos. If you'd like the Amazon Linux team to consider adding ARM NVIDIA packages in addition to x86, I suggest you add your feedback to this ticket here: https://github.com/amazonlinux/amazon-linux-2023/issues/12

I think it's unlikely that ARM NVIDIA packages will be added to AL2, but for AL2023 we are also hoping this request is delivered :)
