### ISSUE TITLE
Support for AL2023 GPU?

### ISSUE THREAD

**Issue by darhsu** [aws/amazon-ecs-ami#234]
Hello, wondering if there are any plans on supporting an Amazon Linux 2023 version with GPUs

**Comment by sparrc** [comment]
Hello, the ECS team is tracking this feature request. We depend on AL2023 having NVIDIA packages available to install via yum. As soon as this is available we will release an AL2023 ECS-Optimized GPU AMI soon after. You can track this feature request to the Amazon Linux team here: https://github.com/amazonlinux/amazon-linux-2023/issues/12

**Comment by harishxr** [comment]
https://github.com/aws/amazon-ecs-ami/pull/370
