### ISSUE TITLE
The version of Docker that is running does not match the version listed in the AMI changelog

### ISSUE THREAD

**Issue by jonaswmoura** [aws/amazon-ecs-ami#304]
### Summary
The version of Docker that is running does not match the version listed in the AMI changelog.

### Description
Hello, good afternoon!
We performed the test with the AMI `amzn2-ami-ecs-kernel-5.10-hvm-2.0.20240821-x86_64-ebs` and observed that it has an outdated docker version when compared to the changelog of the release "ECS optimized AMIs version 20240821" as per the link [releases](https://github.com/aws/amazon-ecs-ami/releases). The description states that it is using docker engine version 25.0.6, as per the image below, however, when starting an instance with the image in question and running the `docker --version` command, version 25.0.5 is shown.

![image](https://github.com/user-attachments/assets/3719d032-5290-45c9-af93-5ac629bf6338)

A detail worth mentioning is that the installed version, if we run the `yum list installed docker` command, returns version 25.0.6, as shown in the image below. In practice, amzn2 has version .6 installed but version .5 running. How would this be possible?

![image](https://github.com/user-attachments/assets/42e249e1-e818-4296-9056-89f09bc4bb0c)

### Expected Behavior
The `docker --version` command outputs version 25.0.6.

### Observed Behavior
-

### Environment Details

- Region: `us-east-1`

- AMI Name: `amzn2-ami-ecs-kernel-5.10-hvm-2.0.20240821-x86_64-ebs`

- AMI Source: `amazon/amzn2-ami-ecs-kernel-5.10-hvm-2.0.20240821-x86_64-ebs`

- EC2 User Data

```shell
#!/bin/bash
cat <<'EOF' >> /etc/ecs/ecs.config
ECS_CLUSTER=unknown
ECS_BACKEND_HOST=
ECS_CONTAINER_INSTANCE_PROPAGATE_TAGS_FROM=ec2_instance
EOF
``` 

### Supporting Log Snippets
-

**Comment by bharat-tft** [comment]
@jonaswmoura We are also facing the same issue. We used the latest Amazon Linux 2 ECS optimized AMI. Release notes says it contains Docker 25.0.6 but in reality it is running with 25.0.5.

**Comment by singholt** [comment]
Hi @jonaswmoura , thank you for reaching out!

25.0.5 is the docker client version whereas 25.0.6 is the docker server version. If you run `docker version` (without the "--") or `docker info`, you would be able to see the above.

So Docker 25.0.6 is running on your instances!
