### ISSUE TITLE
Amazon Linux 2 with kernel 5.10

### ISSUE THREAD

**Issue by zl4bv** [aws/amazon-ecs-ami#35]
### Summary

Requesting a flavor of the Amazon Linux 2 ECS-optimized image with kernel 5.10 instead of the previous kernel 4.14.

### Description

From [this announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/):

> We recommend you use Amazon Linux 2 with kernel 5.10 when launching new instances to benefit from new features and performance improvements. Previous version of the kernel (4.14) will continue to be supported until the [end of life date](https://aws.amazon.com/amazon-linux-2/faqs/)  for Amazon Linux 2 (06/2023).

It would be preferable to have time to transition to the new kernel before the previous kernel goes end of life.

**Comment by carstenblt** [comment]
Any timeline for this?

**Comment by chienhanlin** [comment]
Hello @zl4bv, thanks for submitting this request. 

We do not plan to upgrade the kernel for the ECS optimized Amazon Linux 2 AM. But customers can cherry-pick [this commit](https://github.com/aws/amazon-ecs-ami/commit/ead093e4ca8ffdcbbaf065357b919e56f14f6edc) and try building a custom ECS optimized AL2 AMI with kernel 5.10. 

Thanks.

**Comment by sparrc** [comment]
Additionally we will soon be providing an ECS-optimized [AL2022 preview](https://aws.amazon.com/about-aws/whats-new/2021/11/preview-amazon-linux-2022/) AMI, which will have kernel 5.15.x

**Comment by chienhanlin** [comment]
Hello @zl4bv, Amazon ECS-optimized Amazon Linux 2022 AMI now available in preview
https://aws-preview.aka.amazon.com/about-aws/whats-new/2022/04/amazon-ecs-optimized-linux-2022-ami-available-preview/. Thanks.
