### ISSUE TITLE
ECS cluster meltdown with Docker bug related to FireLens

### ISSUE THREAD

**Issue by elisiariocouto** [aws/amazon-ecs-ami#50]
Hello. Please see the quoted issue. This is stopping us from using FireLens in our ECS clusters.

@elisiariocouto Looks like ECS AMI is on 20.10.7: https://github.com/aws/amazon-ecs-ami/blob/main/release.auto.pkrvars.hcl

So still too old unfortunately. We need 20.10.13:  https://docs.docker.com/engine/release-notes/#201013

_Originally posted by @PettitWesley in https://github.com/aws/amazon-ecs-agent/issues/2787#issuecomment-1111271696_

**Comment by singholt** [comment]
Hi @elisiariocouto, thanks a lot for reporting this. We've released a new set of ECS AMIs with docker 20.10.3 - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html. 

Please re-open this issue if you have any concerns, thanks!
