### ISSUE TITLE
Use gp3 volume for ECS optimized AMIs

### ISSUE THREAD

**Issue by ezwillaws** [aws/amazon-ecs-ami#62]
### Summary

ECS optimized AMIs still use gp2 volumes. It would be great if they used gp3 volumes.

### Description

Amazon EBS gp3 volumes are the latest generation of general-purpose SSD-based EBS volumes that enable customers to provision performance independent of storage capacity, while providing up to 20% lower price per GB than existing gp2 volumes. With gp3 volumes, customers can scale IOPS (input/output operations per second) and throughput without needing to provision additional block storage capacity. This means customers only pay for the storage they need.

**Comment by Realmonia** [comment]
Should be fixed by https://github.com/aws/amazon-ecs-ami/pull/63

**Comment by sparrc** [comment]
closing for the same reason as #63:

> Unfortunately we won't be able to make this change for existing GA AMIs, as it has potential to break customers. Both the AMI description and the default block device mapping volume type are queryable via the ec2 describe-images API, which means customers could be relying on the "gp2" field existing to find the correct and latest AMI.

> See block-device-mapping.volume-type and description under the --filters section of https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html

> We are, however, going to be switching to gp3 for the upcoming AL2022 AMI, which is still in preview: https://github.com/aws/amazon-ecs-ami/pull/72. This will also match what the current base amazon linux 2022 minimal AMI uses as it's default.
