### ISSUE TITLE
Running `make al2arm` fails on the `validate` target

### ISSUE THREAD

**Issue by willroberts** [aws/amazon-ecs-ami#83]
### Summary

Running `REGION=us-east-1 make al2arm` fails on the `validate` target with a "too many open files" error.

### Description

Running `REGION=us-east-1 make al2arm` fails on the `validate` target with a "too many open files" error. Removing the `validate` target from the `al2arm` target in the `Makefile` causes things to work as expected.

### Expected Behavior

`REGION=us-east-1 make al2arm` succeeds without errors.

### Observed Behavior

`REGION=us-east-1 make al2arm` produces the following error:

```
% REGION=us-east-1 make al2arm
./packer init .
./packer validate -var "region=us-east-1" .
Error: failed loading shell
  on al2.pkr.hcl line 140:
  (source code not available)
fork/exec /path/to/amazon-ecs-ami/packer: too many open files
Error: failed loading shell
  on al2.pkr.hcl line 153:
  (source code not available)
pipe: too many open files
Error: failed loading shell
  on al2.pkr.hcl line 158:
  (source code not available)
pipe: too many open files
Error: failed loading shell
  on al2.pkr.hcl line 166:
  (source code not available)
pipe: too many open files
Error: failed loading shell
  on al2.pkr.hcl line 173:
  (source code not available)
pipe: too many open files
Error: failed loading shell
  on al2.pkr.hcl line 177:
  (source code not available)
pipe: too many open files
Error: Failed to load source type
pipe: too many open files
Error: Failed to load source type
pipe: too many open files
Error: Failed to load source type
pipe: too many open files
Error: Failed to load source type
pipe: too many open files
make: *** [validate] Error 1
```

### Environment Details

Apple Macbook Air M2 (ARM64)

Make:
```
% make --version
GNU Make 3.81
This program built for i386-apple-darwin11.3.0
```

Bash:
```
% bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
```

### Supporting Log Snippets

N/A

**Comment by sparrc** [comment]
can you run `ulimit -n` on your laptop and let us know the output? macOS typically sets this limit very low, you might need to increase to something like 2560 with `ulimit -n 2560`

**Comment by willroberts** [comment]
My `ulimit` for new shell sessions is 256 by default.

**Comment by Realmonia** [comment]
@willroberts can you try 2560 or 10240?

**Comment by Realmonia** [comment]
Closing since this is expected to resolve with higher ulimit. Please kindly reopen if you still see the problem
